- name: Comprobar estado de los equipos
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
    - name: Mostrar versión del sistema operativo
      ansible.builtin.shell: lsb_release -d
      register: os_version
      changed_when: false

    - name: Mostrar la versión de Ubuntu
      ansible.builtin.debug:
        msg: "{{ os_version.stdout }}"

    - name: Comprobar actualizaciones disponibles
      ansible.builtin.shell: apt list --upgradable 2>/dev/null | grep -v 'Listing...'
      register: updates
      changed_when: false

    - name: Mostrar actualizaciones pendientes (si hay)
      ansible.builtin.debug:
        msg: >
          {%- if updates.stdout_lines|length > 0 -%}
          Hay actualizaciones pendientes:
          {{ updates.stdout_lines }}
          {%- else -%}
          El sistema está actualizado.
          {%- endif -%}

    - name: Mostrar nombre del equipo
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"
