- name: Instalar y configurar Veyon como cliente
  hosts: pendientes
  become: true
  vars:
    playbook_nombre: "FU07 - configurar_veyon_cliente"
    tarea_1: "Tarea 1 - Instalar Veyon desde .deb"
    tarea_2: "Tarea 2 - Configurar Veyon (clave pública y sin icono)"
    tarea_3: "Tarea 3 - Abrir puertos de Veyon"
    tarea_4: "Tarea 4 - Habilitar y arrancar servicio Veyon"
    veyon_key_filename: "/tmp/veyon_public_key.pem"
    playbooks_root: "{{ playbook_dir | regex_replace('(?s)(.*?/playbooks)(/.*)?', '\\1') }}"

  tasks:
    - name: Tarea 0.1 - Generar timestamp único para esta ejecución
      set_fact:
        playbook_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      run_once: true

    - name: Tarea 0.2 - Desbloquear apt y forzar configuración previa
      block:
        - name: Tarea 0.2.1 - Eliminar locks de apt
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /var/lib/apt/lists/lock
            - /var/cache/apt/archives/lock
            - /var/lib/dpkg/lock
            - /var/lib/dpkg/lock-frontend

        - name: Tarea 0.2.2 - Reparar estado de dpkg si es necesario
          ansible.builtin.command: dpkg --configure -a

        - name: Tarea 0.2.3 - Forzar actualización del caché de paquetes
          apt:
            update_cache: yes
            cache_valid_time: 0
          retries: 3
          delay: 5
          register: resultado_apt_update
          until: resultado_apt_update is succeeded


    # 1. Descargar e instalar Veyon
    - name: Tarea 1.1 - Descargar paquete .deb de Veyon
      get_url:
        url: "{{ veyon_url }}"
        dest: /tmp/veyon.deb
        mode: '0644'

    - name: Tarea 1.2 - Instalar Veyon
      apt:
        deb: /tmp/veyon.deb
      register: resultado_tarea_1
      ignore_errors: true

    - name: Tarea 1.3 - Registrar instalación Veyon en BBDD
      include_tasks: "{{ playbooks_root }}/common/register_task_result.yml"
      vars:
        resultado_tarea: "{{ resultado_tarea_1 }}"
        tarea_nombre: "{{ tarea_1 }}"

    # 2. Configurar Veyon (clave y ocultar icono)
    - name: Tarea 2.1 - Copiar clave pública desde repositorio
      copy:
        src: ../files/public_key.pem
        dest: "{{ veyon_key_filename }}"
        mode: '0644'

    - name: Tarea 2.2 - Importar clave pública
      command: >
        veyon-cli authkeys import alumno/public {{ veyon_key_filename }}
      register: resultado_tarea_2a
      ignore_errors: true

    - name: Tarea 2.3 - Ocultar icono de Veyon
      command: >
        veyon-cli config set Service/HideTrayIcon true
      register: resultado_tarea_2b
      ignore_errors: true

    - name: Tarea 2.4 - Registrar configuración en BBDD
      include_tasks: "{{ playbooks_root }}/common/register_task_result.yml"
      vars:
        resultado_tarea: "{{ resultado_tarea_2b }}"
        tarea_nombre: "{{ tarea_2 }}"

    # 3. Abrir puertos de red
    - name: Tarea 3.1 - Abrir puertos firewall para Veyon
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: [11100, 11200, 11300, 11400]
      register: resultado_tarea_3
      ignore_errors: true

    - name: Tarea 3.2 - Registrar puertos abiertos en BBDD
      include_tasks: "{{ playbooks_root }}/common/register_task_result.yml"
      vars:
        resultado_tarea: "{{ resultado_tarea_3 }}"
        tarea_nombre: "{{ tarea_3 }}"

    # 4. Habilitar servicio
    - name: Tarea 4.1.1 - Registrar el servicio Veyon
      command: veyon-cli service register
      register: resultado_tarea_4_register
      ignore_errors: true

    - name: Tarea 4.1.2 - Iniciar servicio Veyon
      command: veyon-cli service start
      register: resultado_tarea_4_start
      ignore_errors: true

    - name: Tarea 4.2 - Registrar arranque del servicio en BBDD
      include_tasks: "{{ playbooks_root }}/common/register_task_result.yml"
      vars:
        resultado_tarea: "{{ resultado_tarea_4_start }}"
        tarea_nombre: "{{ tarea_4 }}"



    - name: Tarea 5.1 - Validar que Veyon está escuchando en el puerto 11100
      shell: ss -tuln | grep ':11100'
      register: resultado_validacion_veyon
      changed_when: false
      failed_when: resultado_validacion_veyon.rc != 0

    - name: Tarea 6.1 - Asegurar que Wayland está deshabilitado en GDM
      lineinfile:
        path: /etc/gdm3/custom.conf
        regexp: '^#?WaylandEnable='
        line: 'WaylandEnable=false'
        insertafter: '^\[daemon\]'
      notify: Reiniciar GDM
      register: resultado_tarea_6
      ignore_errors: true

    - name: Tarea 6.2 - Registrar configuración de Wayland en BBDD
      include_tasks: "{{ playbooks_root }}/common/register_task_result.yml"
      vars:
        resultado_tarea: "{{ resultado_tarea_6 }}"
        tarea_nombre: "Tarea 6 - Deshabilitar Wayland"

    - name: Tarea 7.1 - Copiar configuración de Veyon desde repositorio
      copy:
        src: ../files/config.json
        dest: /tmp/veyon_config.json
        mode: '0644'

    - name: Tarea 7.2 - Importar configuración de Veyon
      command: >
        veyon-cli config import /tmp/veyon_config.json
      register: resultado_tarea_7
      ignore_errors: true

    - name: Tarea 7.3 - Registrar importación de configuración en BBDD
      include_tasks: "{{ playbooks_root }}/common/register_task_result.yml"
      vars:
        resultado_tarea: "{{ resultado_tarea_7 }}"
        tarea_nombre: "Tarea 7 - Importar configuración de Veyon"

  handlers:
    - name: Reiniciar GDM
      systemd:
        name: gdm
        state: restarted



