---
- name: Prueba de inserción en BBDD
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars_bbdd.yml

  tasks:
    - name: Registrar tarea de prueba en la BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, nombre_tarea, estado, resultado_ok, fecha_ejecucion)
          VALUES ({{ equipo_id }}, '{{ tarea_nombre }}', '{{ estado }}', {{ resultado_ok }}, NOW());
