- name: Configurar restricciones y preferencias para el usuario alumno
  hosts: pendientes
  gather_facts: yes
  become: true

  vars:
    playbook_nombre: "FU06 - configurar_restricciones"
    tarea_1: "Tarea 1 - Restringir modificación de red"
    tarea_2: "Tarea 2 - Impedir cambio de nombre del equipo"
    tarea_3: "Tarea 3 - Configurar energía y pantalla"
    tarea_4: "Tarea 4 - Configurar Firefox en modo incógnito"
    tarea_5: "Tarea 5 - Borrar historial de terminal al cerrar sesión"

  tasks:
    - name: Tarea 0.1 - Generar timestamp único para esta ejecución
      set_fact:
        playbook_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      run_once: true

    - name: Tarea 0.2 - Crear carpeta tmp para Ansible del usuario alumno
      file:
        path: /home/alumno/.ansible/tmp
        state: directory
        owner: alumno
        group: alumno
        mode: '0700'

    
    - name: Tarea 1.1 - Crear política para restringir modificación y desactivación de red
      copy:
        dest: /etc/polkit-1/rules.d/10-network-restrictions.rules
        content: |
          polkit.addRule(function(action, subject) {
            if (subject.user == "alumno" &&
                (
                  action.id == "org.freedesktop.NetworkManager.settings.modify.own" ||
                  action.id == "org.freedesktop.NetworkManager.enable-disable-network" ||
                  action.id == "org.freedesktop.NetworkManager.enable-disable-wifi" ||
                  action.id == "org.freedesktop.NetworkManager.enable-disable-wwan" ||
                  action.id == "org.freedesktop.NetworkManager.network-control"
                )) {
              return polkit.Result.NO;
            }
          });
        owner: root
        group: root
        mode: '0644'

    - name: Tarea 1.2 - Registrar en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_1 }}',
            1,
            'Restricción aplicada',
            'Evita cambios de red por parte de alumno',
            NOW(), NOW()
          );

    - name: Tarea 2.1 - Impedir cambio de nombre del equipo
      copy:
        dest: /etc/polkit-1/rules.d/10-hostname-restriction.rules
        content: |
          polkit.addRule(function(action, subject) {
            if (subject.isInGroup("alumno") &&
                action.id == "org.freedesktop.hostname1.set-hostname") {
              return polkit.Result.NO;
            }
          });
        owner: root
        group: root
        mode: '0644'


    - name: Tarea 2.2 - Registrar en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_2 }}',
            1,
            'Cambio de hostname restringido',
            'Evita que alumno renombre el equipo',
            NOW(), NOW()
          );

    - name: Tarea 3.1 - Crear carpeta de autostart
      file:
        path: /home/alumno/.config/autostart
        state: directory
        owner: alumno
        group: alumno
        mode: '0755'
        
    - name: Tarea 3.2 - Crear script configuración de energía
      copy:
        dest: /home/alumno/.config/scripts/configurar_energia.sh
        content: |
          #!/bin/bash
          export DISPLAY=:0
          export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
          gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
          gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
          gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
          gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 0
        owner: alumno
        group: alumno
        mode: '0755'
    
    - name: Tarea 3.3 - Crear acceso en autostart
      copy:
        dest: /home/alumno/.config/autostart/energia.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Exec=/home/alumno/.config/scripts/configurar_energia.sh
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name=Configuración de energía
        owner: alumno
        group: alumno
        mode: '0644'
    
    - name: Tarea 3.4 - Registrar configuración de energía en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: |
          INSERT INTO tasks (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            'Tarea 3 - Configurar energía en sesión alumno',
            1,
            'Configuración de energía añadida a autostart',
            'Verifica si el usuario ha iniciado sesión gráfica para aplicar los cambios.',
            NOW(),
            NOW()
          );

    - name: Tarea 4.1 - Desactivar guardado de historial en .bashrc
      lineinfile:
        path: /home/alumno/.bashrc
        line: "export HISTFILE=/dev/null"
        create: yes
      become: true
      become_user: alumno

    - name: Tarea 4.1.1 - Asegurar permisos correctos de .bashrc
      file:
        path: /home/alumno/.bashrc
        owner: alumno
        group: alumno
        mode: '0644'
        
    
    - name: Tarea 4.2 - Limpiar historial actual
      copy:
        content: ""
        dest: /home/alumno/.bash_history
        owner: alumno
        group: alumno
        mode: '0600'
    
    - name: Tarea 4.3 - Registrar limpieza de historial en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: |
          INSERT INTO tasks (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            'Tarea 4 - Desactivar historial bash',
            1,
            'Historial de terminal limpiado y desactivado para alumno',
            'Asegúrate de que el usuario no reescriba .bashrc con otro perfil.',
            NOW(),
            NOW()
          );
        



    - name: Tarea 5.1 - Modificar acceso directo de Firefox para abrir en incógnito
      become: true
      copy:
        dest: /var/lib/snapd/desktop/applications/firefox_firefox.desktop
        content: |
          [Desktop Entry]
          Name=Firefox (Incógnito)
          Exec=firefox --private-window %u
          Icon=firefox
          Type=Application
          Categories=Network;WebBrowser;
        owner: root
        group: root
        mode: '0644'


    - name: Tarea 5.2 - Registrar configuración Firefox en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_4 }}',
            1,
            'Firefox abre en modo incógnito',
            'Se ha modificado el .desktop para firefox',
            NOW(), NOW()
          );