- name: Configurar restricciones y preferencias para el usuario alumno
  hosts: pendientes
  gather_facts: yes
  become: true

  vars:
    playbook_nombre: "FU06 - configurar_restricciones"
    tarea_1: "Tarea 1 - Restringir modificación de red"
    tarea_2: "Tarea 2 - Impedir cambio de nombre del equipo"
    tarea_3: "Tarea 3 - Configurar energía y pantalla"
    tarea_4: "Tarea 4 - Configurar Firefox en modo incógnito"
    tarea_5: "Tarea 5 - Borrar historial de terminal al cerrar sesión"

  tasks:
    - name: Tarea 0 - Generar timestamp único para esta ejecución
      set_fact:
        playbook_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      run_once: true
    
    - name: Tarea 1.1 - Crear política para restringir modificación y desactivación de red
      copy:
        dest: /etc/polkit-1/rules.d/10-network-restrictions.rules
        content: |
          polkit.addRule(function(action, subject) {
            if (subject.user == "alumno" &&
                (
                  action.id == "org.freedesktop.NetworkManager.settings.modify.own" ||
                  action.id == "org.freedesktop.NetworkManager.enable-disable-network" ||
                  action.id == "org.freedesktop.NetworkManager.enable-disable-wifi" ||
                  action.id == "org.freedesktop.NetworkManager.enable-disable-wwan"
                )) {
              return polkit.Result.NO;
            }
          });
        owner: root
        group: root
        mode: '0644'



    - name: Tarea 1.2 - Registrar en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_1 }}',
            1,
            'Restricción aplicada',
            'Evita cambios de red por parte de alumno',
            NOW(), NOW()
          );

    - name: Tarea 2.1 - Impedir cambio de nombre del equipo
      copy:
        dest: /etc/polkit-1/rules.d/10-hostname-restriction.rules
        content: |
          polkit.addRule(function(action, subject) {
            if (subject.isInGroup("alumno") &&
                action.id == "org.freedesktop.hostname1.set-hostname") {
              return polkit.Result.NO;
            }
          });
        owner: root
        group: root
        mode: '0644'


    - name: Tarea 2.2 - Registrar en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_2 }}',
            1,
            'Cambio de hostname restringido',
            'Evita que alumno renombre el equipo',
            NOW(), NOW()
          );

    - name: Tarea 3.1 - Desactivar apagado de pantalla para alumno
      become: true
      become_user: alumno
      shell: |
        export DISPLAY=:0
        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
        gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
        gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0
        gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
        gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 0
      environment:
        XDG_RUNTIME_DIR: "/run/user/1000"
      register: resultado_energia
      ignore_errors: true


    - name: Tarea 3.2 - Registrar configuración de energía en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_3 }}',
            1,
            'Modo rendimiento y sin suspensión de pantalla',
            'Aplicado con gsettings y powerprofilesctl',
            NOW(), NOW()
          );

    - name: Tarea 4.1 - Modificar acceso directo de Firefox
      lineinfile:
        path: /usr/share/applications/firefox.desktop
        regexp: '^Exec='
        line: 'Exec=firefox --private-window'

    - name: Tarea 4.2 - Registrar configuración Firefox en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_4 }}',
            1,
            'Firefox abre en modo incógnito',
            'Se ha modificado el .desktop para firefox',
            NOW(), NOW()
          );

    - name: Tarea 5.1 - Borrar historial de terminal al salir
      lineinfile:
        path: /home/alumno/.bash_logout
        line: 'cat /dev/null > ~/.bash_history && history -c'
        create: yes
        owner: alumno
        group: alumno
        mode: '0644'

    - name: Tarea 5.2 - Registrar limpieza de historial en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_5 }}',
            1,
            'Historial de terminal se borra al salir',
            'Configurado en .bash_logout',
            NOW(), NOW()
          );
