- name: Instalar VS Code, Android Studio y VirtualBox
  hosts: pendientes
  gather_facts: no
  become: true

  vars:
    playbook_nombre: "FU05 - instalar_programas"
    tarea_1: "Tarea 1 - Instalar VS Code"
    tarea_2: "Tarea 2 - Instalar Android Studio"
    tarea_3: "Tarea 3 - Instalar VirtualBox"

  tasks:
    - name: Tarea 0 - Generar timestamp único para esta ejecución
      set_fact:
        playbook_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      run_once: true

# ---------- VS CODE ----------
    - name: Tarea 1.1 - Añadir repositorio de VS Code
      shell: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/microsoft.gpg
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
      args:
        executable: /bin/bash
      register: resultado_repo_vscode
      changed_when: true
      ignore_errors: true

    - name: Tarea 1.2 - Instalar VS Code
      ansible.builtin.apt:
        name: code
        update_cache: yes
        state: present
      register: resultado_tarea_1
      ignore_errors: true

    - name: Tarea 1.3 - Mensaje de ayuda si falla VS Code
      set_fact:
        help_message_1: "Verifica conectividad o que se haya añadido correctamente el repositorio de Microsoft."
        is_ok_1: 0
      when: resultado_tarea_1.unreachable | default(false) or
            (resultado_tarea_1.rc is defined and resultado_tarea_1.rc != 0)

    - name: Tarea 1.4 - Registrar resultado en BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_1 }}',
            {{ is_ok_1 | default(1) }},
            '{{ resultado_tarea_1 | to_json | replace("'", "''") }}',
            '{{ help_message_1 | default("") | replace("'", "''") }}',
            NOW(), NOW()
          );
      delegate_to: localhost
      become: false

# ---------- ANDROID STUDIO ----------
    - name: Tarea 2.1 - Instalar Android Studio vía Snap
      community.general.snap:
        name: android-studio
        classic: yes
        state: present
      register: resultado_tarea_2
      ignore_errors: true

    - name: Tarea 2.2 - Mensaje de ayuda si falla Android Studio
      set_fact:
        help_message_2: "Verifica que Snap esté instalado y funcionando correctamente."
        is_ok_2: 0
      when: resultado_tarea_2.unreachable | default(false) or
            (resultado_tarea_2.rc is defined and resultado_tarea_2.rc != 0)

    - name: Tarea 2.3 - Registrar resultado en BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_2 }}',
            {{ is_ok_2 | default(1) }},
            '{{ resultado_tarea_2 | to_json | replace("'", "''") }}',
            '{{ help_message_2 | default("") | replace("'", "''") }}',
            NOW(), NOW()
          );
      delegate_to: localhost
      become: false

# ---------- VIRTUALBOX ----------
    - name: Tarea 3.1 - Instalar VirtualBox
      ansible.builtin.apt:
        name: virtualbox
        state: present
        update_cache: yes
      register: resultado_tarea_3
      ignore_errors: true

    - name: Tarea 3.2 - Mensaje de ayuda si falla VirtualBox
      set_fact:
        help_message_3: "Verifica que el kernel tenga soporte o que el repositorio esté disponible."
        is_ok_3: 0
      when: resultado_tarea_3.unreachable | default(false) or
            (resultado_tarea_3.rc is defined and resultado_tarea_3.rc != 0)

    - name: Tarea 3.3 - Registrar resultado en BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_3 }}',
            {{ is_ok_3 | default(1) }},
            '{{ resultado_tarea_3 | to_json | replace("'", "''") }}',
            '{{ help_message_3 | default("") | replace("'", "''") }}',
            NOW(), NOW()
          );
      delegate_to: localhost
      become: false
