- name: Instalar programas de desarrollo (VS Code)
  hosts: pendientes
  gather_facts: no
  become: true

  vars:
    playbook_nombre: "FU05.1 - instalar_vscode"
    tarea_1: "Tarea 1 - Añadir repos Visual Studio Code"
    tarea_2: "Tarea 2 - Instalar VS Code"

  tasks:
    - name: Tarea 0 - Generar timestamp único para esta ejecución
      set_fact:
        playbook_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      run_once: true


    - name: Tarea 1.1 - Importar clave y añadir repo VSCode
      block:

        - name: Importar clave GPG de Microsoft para VSCode
          ansible.builtin.apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            state: present
          register: resultado_importar_clave

        - name: Añadir repositorio de Visual Studio Code
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
            filename: 'vscode'
            state: present
          register: resultado_anadir_repo

      rescue:
        - name: Mensaje de ayuda si falla la configuración del repositorio de VSCode
          debug:
            msg: "❌ No se pudo añadir el repositorio de Visual Studio Code. Revisa la conexión o la URL del repositorio."

      always:
        - name: Tarea 1.2 - Registrar resultado de la configuración del repositorio en BBDD
          delegate_to: localhost
          become: false
          community.mysql.mysql_query:
            login_db: "{{ db_name }}"
            login_user: "{{ db_user }}"
            login_password: "{{ db_password }}"
            login_host: "{{ db_host }}"
            query: |
              INSERT INTO tasks (
                host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
              ) VALUES (
                {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
                '{{ playbook_nombre }}',
                '{{ playbook_id }}',
                '{{ tarea_1 }}',
                {{ (resultado_anadir_repo is defined and resultado_anadir_repo.failed | default(false) == false) | int }},
                '{{ resultado_anadir_repo.msg | default("OK") }}',
                '{% if resultado_anadir_repo is not defined or resultado_anadir_repo.failed | default(false) %}Error al añadir el repositorio de VSCode. Verifica la clave o la URL.{% else %}OK{% endif %}',
                now(),
                now()
              )
              
    - name: Tarea 2.1 - Instalar Visual Studio Code
      ansible.builtin.apt:
        name: code
        state: present
        update_cache: yes
      register: resultado_instalacion_vscode
      ignore_errors: true

    - name: Tarea 2.2 - Registrar instalación de VSCode en BBDD
      delegate_to: localhost
      become: false
      community.mysql.mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_host }}"
        query: >
          INSERT INTO {{ db_table }} (
            host_id, playbook, playbook_uid, task_name, is_ok, task_message, help_message, created, modified
          ) VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_2 }}',
            {{ 0 if resultado_instalacion_vscode.rc is defined and resultado_instalacion_vscode.rc != 0 else 1 }},
            '{{ resultado_instalacion_vscode | to_json | replace("'", "''") }}',
            'Verifica que el repositorio se añadió correctamente y que tienes conexión a internet.',
            NOW(),
            NOW()
          );

# ---------- ACCESOS DIRECTOS ----------
    - name: Tarea 3.1 - Crear carpeta de accesos directos si no existe
      file:
        path: /home/alumno/.local/share/applications
        state: directory
        owner: alumno
        group: alumno
        mode: '0755'

    - name: Tarea 3.2 - Crear acceso directo a VSCode
      copy:
        dest: /home/alumno/.local/share/applications/vscode.desktop
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Visual Studio Code
          Exec=/usr/bin/code
          Icon=code
          Terminal=false
          Categories=Development;IDE;
        owner: alumno
        group: alumno
        mode: '0755'