---
- name: Añadir usuario temporal con sudo
  hosts: pendientes
  gather_facts: no
  become: false

  vars:
    tarea_1: "Recolectar datos del sistema"
    tarea_2: "Crear usuario temporal"
    playbook_nombre: "crear_usuario_temporal"
    playbook_id: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"  # timestamp único por ejecución

  tasks:
    - name: Tarea 1 - Recolectar datos del sistema
      setup:
      register: resultado_tarea_1
      ignore_unreachable: true
      ignore_errors: true

    - name: Registrar resultado tarea 1 en BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, playbook, playbook_uid, nombre_tarea, correcta, resultado, mensaje_error, fecha_ejecucion)
          VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_1 }}',
            {{ 1 if resultado_tarea_1 is succeeded else 0 }},
            '{{ "ok" if resultado_tarea_1 is succeeded else "error" }}',
            '{{ resultado_tarea_1.msg | default("") }}',
            NOW()
          );
      delegate_to: localhost
      ignore_errors: true

    - name: Tarea 2 - Crear usuario temporal
      ansible.builtin.user:
        name: ansible_temp
        password: "{{ ansible_temp_password }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      become: true
      when: resultado_tarea_1 is succeeded
      register: resultado_tarea_2
      ignore_errors: true
      ignore_unreachable: true

    - name: Registrar resultado tarea 2 en BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, playbook, playbook_uid, nombre_tarea, correcta, resultado, mensaje_error, fecha_ejecucion)
          VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ playbook_nombre }}',
            '{{ playbook_id }}',
            '{{ tarea_2 }}',
            {{ 1 if resultado_tarea_2 is succeeded else 0 }},
            '{{ "ok" if resultado_tarea_2 is succeeded else "error" }}',
            '{{ resultado_tarea_2.msg | default("") }}',
            NOW()
          );
      delegate_to: localhost
      ignore_errors: true
