---
- name: Añadir usuario temporal con sudo
  hosts: pendientes
  gather_facts: no
  become: false

  tasks:

    - name: Recolectar datos del sistema
      setup:
      register: setup_result
      ignore_unreachable: true

    - name: Crear usuario temporal
      ansible.builtin.user:
        name: ansible_temp
        password: "{{ ansible_temp_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      become: true
      when: setup_result is succeeded
      register: create_user_result
      ignore_errors: true

    - name: Guardar resultados para registrar más tarde
      set_fact:
        resultado_tarea: "{{ 'ok' if create_user_result is succeeded else 'error' }}"
        resultado_ok: "{{ 1 if create_user_result is succeeded else 0 }}"
        resultado_mensaje: "{{ create_user_result.msg | default('') }}"
      when: setup_result is defined
      ignore_errors: true

    - name: Registrar resultados en la BBDD
      hosts: localhost
      gather_facts: no
      vars:
        tarea_nombre: "crear_usuario_temporal"

  tasks:

    - name: Registrar resultados en la base de datos
      community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, nombre_tarea, estado, resultado_ok, fecha_ejecucion)
          VALUES (
            '{{ hostvars[item].equipo_id | default("NULL") }}',
            '{{ tarea_nombre }}',
            '{{ hostvars[item].resultado_tarea | default("error") }}',
            {{ hostvars[item].resultado_ok | default(0) }},
            NOW()
          );
      loop: "{{ groups['pendientes'] }}"
      when: hostvars[item].equipo_id is defined
