---
- name: Añadir usuario temporal con sudo
  hosts: all
  gather_facts: no
  ignore_unreachable: yes  # Esto es clave

  vars:
    tarea_nombre: "crear_usuario_temporal"
    db_name: "aula_monitor"
    db_table: "tareas"
    db_user: "{{ db_user }}"          # viene de la encuesta
    db_password: "{{ db_password }}"  # viene de la encuesta

  tasks:

    - name: Recolectar datos del sistema
      setup:
      ignore_errors: yes  # Para que siga el play aunque falle
      register: setup_result

    - name: Registrar resultado en la BBDD
      community.mysql.mysql_query:
        login_user: "{{ hostvars['localhost']['db_user'] }}"
        login_password: "{{ hostvars['localhost']['db_password'] }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, nombre_tarea, estado, resultado_ok, fecha_ejecucion)
          VALUES (
            '{{ hostvars[inventory_hostname].equipo_id | default("NULL") }}',
            '{{ tarea_nombre }}',
            '{{ "ok" if setup_result is succeeded else "error" }}',
            {{ 1 if setup_result is succeeded else 0 }},
            NOW()
          );
      delegate_to: localhost
      when: "'db_user' in hostvars['localhost'] and 'db_password' in hostvars['localhost']"

