---
- name: Añadir usuario temporal con sudo
  hosts: pendientes
  gather_facts: no
  become: false

  tasks:

    - name: Recolectar datos del sistema
      setup:
      register: setup_result
      ignore_unreachable: true

    - name: Crear usuario temporal
      ansible.builtin.user:
        name: ansible_temp
        password: "{{ ansible_temp_password }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      become: true
      when: setup_result is succeeded
      register: create_user_result
      ignore_errors: true

    - name: Guardar resultados para registrar más tarde
      set_fact:
        tarea_nombre: "crear_usuario_temporal"
        resultado_tarea: "{{ 'ok' if create_user_result is succeeded else 'error' }}"
        resultado_ok: "{{ 1 if create_user_result is succeeded else 0 }}"
        resultado_mensaje: "{{ create_user_result.msg | default('') }}"
      when: setup_result is defined
      ignore_errors: true

    - name: Registrar resultados en la BBDD
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, nombre_tarea, correcta, resultado, fecha_ejecucion)
          VALUES (
            {{ hostvars[inventory_hostname].equipo_id | default('NULL') }},
            '{{ hostvars[inventory_hostname].tarea_nombre | default("desconocida") }}',
            {{ hostvars[inventory_hostname].resultado_ok | default(0) }},
            '{{ hostvars[inventory_hostname].resultado_tarea | default("error") }}',
            NOW()
          );
      delegate_to: localhost
      run_once: false
      ignore_errors: true
      ignore_unreachable: true
      when: hostvars[inventory_hostname].equipo_id is defined

