- name: Añadir usuario temporal con sudo
  hosts: all
  gather_facts: no
  vars:
    tarea_nombre: "crear_usuario"
  tasks:

    - name: Intentar conexión y recopilar facts
      block:
        - name: Recolectar datos del sistema
          ansible.builtin.setup:
          register: setup_result

        - name: Añadir usuario temporal
          ansible.builtin.user:
            name: ansible_temp
            password: "{{ '1234' | password_hash('sha512') }}"
            shell: /bin/bash
            groups: sudo
            append: yes
          become: yes

      rescue:
        - name: Guardar fallo en la base de datos (sin conexión)
          include_tasks: registrar_tarea.yml
          vars:
            resultado: "Fallo de conexión SSH"
            correcta: "0"
            equipo_id: "{{ equipo_id | default('desconocido') }}"
            tarea_nombre: "{{ tarea_nombre }}"
            tiempo: "{{ ansible_date_time.iso8601 }}"
          run_once: true

      always:
        - name: Registrar éxito (si no hubo errores)
          when: setup_result is defined and setup_result.failed is not defined
          include_tasks: registrar_tarea.yml
          vars:
            resultado: "Usuario creado correctamente"
            correcta: "1"
            equipo_id: "{{ equipo_id }}"
            tarea_nombre: "{{ tarea_nombre }}"
            tiempo: "{{ ansible_date_time.iso8601 }}"
