---
- name: Añadir usuario temporal con sudo
  hosts: pendientes
  gather_facts: no
  become: false

  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:

    - name: Recolectar datos del sistema
      setup:
      register: setup_result
      ignore_unreachable: true

    - name: Crear usuario temporal
      ansible.builtin.user:
        name: ansible_temp
        password: "{{ ansible_temp_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
      become: true
      when: setup_result is succeeded

    - name: Registrar resultado en la BBDD
      community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_db: "{{ db_name }}"
        query: >
          INSERT INTO {{ db_table }} (equipo_id, nombre_tarea, estado, resultado_ok, fecha_ejecucion)
          VALUES (
            '{{ hostvars[inventory_hostname].equipo_id | default("NULL") }}',
            '{{ tarea_nombre }}',
            '{{ "ok" if setup_result is succeeded else "error" }}',
            {{ 1 if setup_result is succeeded else 0 }},
            NOW()
          );
      delegate_to: localhost
      when: db_user is defined and db_password is defined
