- name: Comprobar estado de los equipos
  hosts: all
  gather_facts: true

  tasks:
    - name: Mostrar nombre del equipo
      ansible.builtin.debug:
        msg: "Nombre del host: {{ inventory_hostname }}"

    - name: Mostrar versi칩n de Ubuntu
      ansible.builtin.command: lsb_release -d
      register: ubuntu_version

    - name: Reportar versi칩n
      ansible.builtin.debug:
        msg: "Versi칩n Ubuntu: {{ ubuntu_version.stdout }}"

    - name: Comprobar actualizaciones disponibles
      ansible.builtin.command: apt list --upgradable
      register: updates
      changed_when: false

    - name: Procesar lista de actualizaciones
      ansible.builtin.set_fact:
        updates_list: "{{ updates.stdout_lines | select('match', '^.+/') | list }}"

    - name: Mostrar actualizaciones
      ansible.builtin.debug:
        msg: >
          {% if updates_list|length > 0 %}
            Hay {{ updates_list | length }} actualizaciones:
            {{ updates_list }}
          {% else %}
            El sistema est치 actualizado.
          {% endif %}

    - name: Registrar resumen como stats
      ansible.builtin.set_stats:
        data:
          equipo: "{{ inventory_hostname }}"
          version: "{{ ubuntu_version.stdout }}"
          actualizaciones: "{{ updates_list | length }}"
